version: '3.8'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - STEAM_TOKEN=${STEAM_TOKEN}
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "80:80"
    restart: always